# Generated by Django 3.2.16 on 2023-04-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_auto_20230428_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='penalty_reason',
            field=models.CharField(blank=True, choices=[('late_return', 'Late return'), ('damage', 'Damage'), ('loss', 'Loss'), ('overdue', 'Overdue')], max_length=20, null=True),
        ),
    ]
