# Generated by Django 3.2.16 on 2023-05-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_alter_payment_penalty_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancelledbook',
            name='reason',
        ),
    ]
