# Generated by Django 3.2.16 on 2023-05-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0006_auto_20230503_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('return_date', models.DateField(auto_now_add=True)),
                ('over_due', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('reason', models.CharField(max_length=50)),
                ('total', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.book')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.issuebook')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.member')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
        migrations.RemoveField(
            model_name='returnbook',
            name='penalty_reason',
        ),
        migrations.AddField(
            model_name='returnbook',
            name='book',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='library_app.book'),
            preserve_default=False,
        ),
    ]
