# Generated by Django 3.2.16 on 2023-05-05 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0007_auto_20230505_1229'),
    ]

    operations = [
    ]
